/**
 * indian-foods.ts — a built-in table of common Indian foods with per-serving
 * macros. This is the stub the app ships with so search-by-name works today,
 * before the FatSecret + Gemini backend is wired in.
 *
 * Values are reasonable home-portion estimates (1 katori ≈ 150g cooked). They
 * are good enough for early feedback; FatSecret will supersede them for
 * precision. `aliases` widen matching (chapati ↔ roti, curd ↔ dahi, etc.).
 */

export interface IndianFood {
  id: string;
  name: string;
  serving: string;
  kcal: number;
  proteinG: number;
  carbsG: number;
  fatG: number;
  aliases?: string[];
}

export const INDIAN_FOODS: IndianFood[] = [
  // Breads
  {
    id: 'roti',
    name: 'Roti / Chapati',
    serving: '1 piece (40g)',
    kcal: 120,
    proteinG: 3,
    carbsG: 18,
    fatG: 3,
    aliases: ['chapati', 'phulka', 'rotli'],
  },
  {
    id: 'paratha',
    name: 'Plain Paratha',
    serving: '1 piece',
    kcal: 200,
    proteinG: 4,
    carbsG: 28,
    fatG: 8,
  },
  {
    id: 'aloo-paratha',
    name: 'Aloo Paratha',
    serving: '1 piece',
    kcal: 260,
    proteinG: 6,
    carbsG: 36,
    fatG: 10,
    aliases: ['potato paratha'],
  },
  {
    id: 'naan',
    name: 'Plain Naan',
    serving: '1 piece',
    kcal: 260,
    proteinG: 8,
    carbsG: 45,
    fatG: 5,
  },
  {
    id: 'butter-naan',
    name: 'Butter Naan',
    serving: '1 piece',
    kcal: 320,
    proteinG: 8,
    carbsG: 45,
    fatG: 12,
  },
  {
    id: 'puri',
    name: 'Puri',
    serving: '1 piece',
    kcal: 100,
    proteinG: 2,
    carbsG: 12,
    fatG: 5,
  },

  // Rice
  {
    id: 'rice',
    name: 'White Rice',
    serving: '1 katori (150g)',
    kcal: 200,
    proteinG: 4,
    carbsG: 44,
    fatG: 1,
    aliases: ['rice', 'chawal', 'steamed rice', 'plain rice'],
  },
  {
    id: 'jeera-rice',
    name: 'Jeera Rice',
    serving: '1 katori',
    kcal: 240,
    proteinG: 4,
    carbsG: 42,
    fatG: 6,
  },
  {
    id: 'veg-biryani',
    name: 'Veg Biryani',
    serving: '1 plate (250g)',
    kcal: 350,
    proteinG: 8,
    carbsG: 55,
    fatG: 11,
  },
  {
    id: 'chicken-biryani',
    name: 'Chicken Biryani',
    serving: '1 plate (250g)',
    kcal: 450,
    proteinG: 22,
    carbsG: 50,
    fatG: 18,
  },
  {
    id: 'khichdi',
    name: 'Dal Khichdi',
    serving: '1 katori',
    kcal: 200,
    proteinG: 7,
    carbsG: 35,
    fatG: 4,
  },

  // Dals & legumes
  {
    id: 'dal-tadka',
    name: 'Dal Tadka',
    serving: '1 katori (150g)',
    kcal: 150,
    proteinG: 8,
    carbsG: 20,
    fatG: 4,
    aliases: ['dal', 'daal', 'yellow dal'],
  },
  {
    id: 'dal-makhani',
    name: 'Dal Makhani',
    serving: '1 katori',
    kcal: 280,
    proteinG: 9,
    carbsG: 20,
    fatG: 18,
  },
  {
    id: 'rajma',
    name: 'Rajma',
    serving: '1 katori',
    kcal: 210,
    proteinG: 9,
    carbsG: 30,
    fatG: 6,
    aliases: ['kidney beans'],
  },
  {
    id: 'chole',
    name: 'Chole / Chana Masala',
    serving: '1 katori',
    kcal: 230,
    proteinG: 10,
    carbsG: 28,
    fatG: 9,
    aliases: ['chana', 'chickpea curry'],
  },
  {
    id: 'sambar',
    name: 'Sambar',
    serving: '1 katori',
    kcal: 110,
    proteinG: 5,
    carbsG: 15,
    fatG: 3,
  },

  // Paneer & veg
  {
    id: 'paneer-butter-masala',
    name: 'Paneer Butter Masala',
    serving: '1 katori',
    kcal: 320,
    proteinG: 12,
    carbsG: 12,
    fatG: 25,
    aliases: ['paneer makhani'],
  },
  {
    id: 'palak-paneer',
    name: 'Palak Paneer',
    serving: '1 katori',
    kcal: 250,
    proteinG: 12,
    carbsG: 10,
    fatG: 18,
  },
  {
    id: 'paneer-tikka',
    name: 'Paneer Tikka',
    serving: '100g',
    kcal: 270,
    proteinG: 16,
    carbsG: 8,
    fatG: 19,
  },
  {
    id: 'paneer-raw',
    name: 'Paneer (raw)',
    serving: '100g',
    kcal: 296,
    proteinG: 18,
    carbsG: 4,
    fatG: 22,
    aliases: ['cottage cheese'],
  },
  {
    id: 'mixed-veg',
    name: 'Mixed Veg Sabzi',
    serving: '1 katori',
    kcal: 120,
    proteinG: 3,
    carbsG: 12,
    fatG: 7,
    aliases: ['sabzi', 'subzi'],
  },
  {
    id: 'bhindi',
    name: 'Bhindi Sabzi',
    serving: '1 katori',
    kcal: 140,
    proteinG: 3,
    carbsG: 10,
    fatG: 10,
    aliases: ['okra'],
  },
  {
    id: 'aloo-gobi',
    name: 'Aloo Gobi',
    serving: '1 katori',
    kcal: 150,
    proteinG: 4,
    carbsG: 18,
    fatG: 8,
  },

  // South Indian
  {
    id: 'idli',
    name: 'Idli',
    serving: '2 pieces',
    kcal: 140,
    proteinG: 4,
    carbsG: 28,
    fatG: 1,
  },
  {
    id: 'dosa',
    name: 'Plain Dosa',
    serving: '1 piece',
    kcal: 170,
    proteinG: 4,
    carbsG: 26,
    fatG: 6,
  },
  {
    id: 'masala-dosa',
    name: 'Masala Dosa',
    serving: '1 piece',
    kcal: 250,
    proteinG: 6,
    carbsG: 36,
    fatG: 9,
  },
  {
    id: 'upma',
    name: 'Upma',
    serving: '1 katori',
    kcal: 250,
    proteinG: 6,
    carbsG: 38,
    fatG: 8,
  },
  {
    id: 'poha',
    name: 'Poha',
    serving: '1 plate',
    kcal: 270,
    proteinG: 6,
    carbsG: 45,
    fatG: 7,
  },
  {
    id: 'vada',
    name: 'Medu Vada',
    serving: '1 piece',
    kcal: 130,
    proteinG: 4,
    carbsG: 14,
    fatG: 7,
  },

  // Non-veg
  {
    id: 'chicken-curry',
    name: 'Chicken Curry',
    serving: '1 katori (150g)',
    kcal: 250,
    proteinG: 22,
    carbsG: 8,
    fatG: 15,
  },
  {
    id: 'chicken-tikka',
    name: 'Chicken Tikka',
    serving: '100g',
    kcal: 220,
    proteinG: 30,
    carbsG: 4,
    fatG: 9,
  },
  {
    id: 'butter-chicken',
    name: 'Butter Chicken',
    serving: '1 katori',
    kcal: 330,
    proteinG: 22,
    carbsG: 10,
    fatG: 22,
    aliases: ['murgh makhani'],
  },
  {
    id: 'egg-curry',
    name: 'Egg Curry (2 eggs)',
    serving: '1 katori',
    kcal: 240,
    proteinG: 14,
    carbsG: 8,
    fatG: 17,
  },
  {
    id: 'boiled-egg',
    name: 'Boiled Egg',
    serving: '1 egg',
    kcal: 78,
    proteinG: 6,
    carbsG: 1,
    fatG: 5,
    aliases: ['anda', 'egg'],
  },
  {
    id: 'fish-curry',
    name: 'Fish Curry',
    serving: '1 katori',
    kcal: 200,
    proteinG: 20,
    carbsG: 6,
    fatG: 11,
  },

  // Dairy / sides / snacks
  {
    id: 'dahi',
    name: 'Curd / Dahi',
    serving: '1 katori (150g)',
    kcal: 90,
    proteinG: 5,
    carbsG: 7,
    fatG: 4,
    aliases: ['curd', 'yogurt', 'yoghurt'],
  },
  {
    id: 'raita',
    name: 'Raita',
    serving: '1 katori',
    kcal: 100,
    proteinG: 4,
    carbsG: 8,
    fatG: 5,
  },
  {
    id: 'samosa',
    name: 'Samosa',
    serving: '1 piece',
    kcal: 260,
    proteinG: 4,
    carbsG: 28,
    fatG: 15,
  },
  {
    id: 'pakora',
    name: 'Pakora',
    serving: '100g',
    kcal: 320,
    proteinG: 7,
    carbsG: 30,
    fatG: 18,
    aliases: ['bhaji', 'bhajiya'],
  },

  // Drinks & sweets
  {
    id: 'chai',
    name: 'Masala Chai',
    serving: '1 cup',
    kcal: 90,
    proteinG: 3,
    carbsG: 12,
    fatG: 3,
    aliases: ['tea', 'chaai'],
  },
  {
    id: 'lassi',
    name: 'Sweet Lassi',
    serving: '1 glass',
    kcal: 220,
    proteinG: 6,
    carbsG: 35,
    fatG: 6,
  },
  {
    id: 'gulab-jamun',
    name: 'Gulab Jamun',
    serving: '1 piece',
    kcal: 150,
    proteinG: 2,
    carbsG: 25,
    fatG: 5,
  },
  {
    id: 'banana',
    name: 'Banana',
    serving: '1 medium',
    kcal: 105,
    proteinG: 1,
    carbsG: 27,
    fatG: 0,
    aliases: ['kela'],
  },
];
